#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

mode="interactive"
case "${1:-}" in
  "") ;;
  --no-push) mode="no-push" ;;
  --draft-pr) mode="draft-pr" ;;
  *)
    echo "Usage: $0 [--no-push|--draft-pr]" >&2
    exit 64
    ;;
esac

if [[ "$mode" == "draft-pr" ]]; then
  branch=$(git branch --show-current)
  if [[ -z "$branch" || "$branch" == "main" ]]; then
    echo "--draft-pr requires a dedicated non-main worktree branch." >&2
    exit 1
  fi
  if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "--draft-pr requires a clean worktree before generating the inventory." >&2
    exit 1
  fi
fi

./scripts/generate-inventory.sh
git add README.md LICENSE .gitignore docs scripts inventory/pi-inventory.json

if git diff --cached --quiet; then
  echo "No safe inventory or documentation changes to commit."
  exit 0
fi

./scripts/check-public.sh
git diff --cached --stat
git diff --cached

if [[ "$mode" == "interactive" || "$mode" == "no-push" ]]; then
  read -r -p "Create this local commit? [y/N] " answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    echo "Cancelled before commit."
    exit 0
  fi
fi

git commit -m "chore: update Pi setup inventory"

if [[ "$mode" == "no-push" ]]; then
  echo "Committed locally. Push when ready with: git push"
  exit 0
fi

if [[ "$mode" == "draft-pr" ]]; then
  git push --set-upstream origin "$branch"
  pr_url=$(gh pr list --head "$branch" --base main --state open --json url --jq '.[0].url' 2>/dev/null || true)
  if [[ -z "$pr_url" ]]; then
    pr_url=$(gh pr create --draft --base main \
      --title "chore: update Pi setup inventory" \
      --body "Automated safe inventory update. Generated by the approved weekly maintenance workflow; review the public-safe diff and validation before merging.")
  fi
  echo "Draft PR ready: $pr_url"
  exit 0
fi

read -r -p "Push this public commit to origin? [y/N] " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then
  git push
else
  echo "Committed locally; not pushed."
fi
